### ISSUE TITLE
[SERIOUS PROBLEM]Compilation error in got10k/datasets/lasot.py

### ISSUE THREAD

**Issue by fzh0917** [got-10k/toolkit#32]
As the title said, there is a compilation error in the file `got10k/datasets/lasot.py`. The code is `self._check_integrity(root_dir, subset)`  at the line # [31](https://github.com/got-10k/toolkit/blob/83aafbf4345d1640eac33a39d98b0fa103a92c6d/got10k/datasets/lasot.py#L31), passing 2 parameters into the function `self._check_integrity`. However, it just receives one argument in its [definition](https://github.com/got-10k/toolkit/blob/83aafbf4345d1640eac33a39d98b0fa103a92c6d/got10k/datasets/lasot.py#L84). So, a compilation error happened when I run my code. 
The error info is as the following.
```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    main()
  File "train.py", line 14, in main
    tracker.train1(data_path, net_storage_dir)
  File ".../.../xxx.py", line 177, in train1
    LaSOT(os.path.join(data_path, 'LaSOT/LaSOTBenchmark'), subset='train')
  File ".../.../anaconda3/lib/python3.6/site-packages/got10k/datasets/lasot.py", line 31, in __init__
    self._check_integrity(root_dir, subset)
TypeError: _check_integrity() takes 2 positional arguments but 3 were given
```

**Comment by wWHWw** [comment]
@fzh0917  hi i met the same problem, any idea how to solve it?

**Comment by wWHWw** [comment]
i also want to know where i can get lasot.json for training?
