### ISSUE TITLE
Exception: Dataset not found or corrupted.

### ISSUE THREAD

**Issue by Sibozhu** [got-10k/toolkit#43]
Hello @huanglianghua ,

Thank you for this amazing toolkit. I'm trying to use UAV123 dataset from your toolkit and ran into the error says that:

```
Traceback (most recent call last):
  File "run_tracking.py", line 20, in <module>
    ExperimentUAV123('data/UAV123', version='UAV123'),
  File "/home/sibobobo/.local/lib/python3.6/site-packages/got10k/experiments/uav123.py", line 24, in __init__
    self.dataset = UAV123(root_dir, version)
  File "/home/sibobobo/.local/lib/python3.6/site-packages/got10k/datasets/uav123.py", line 29, in __init__
    self._check_integrity(root_dir, version)
  File "/home/sibobobo/.local/lib/python3.6/site-packages/got10k/datasets/uav123.py", line 98, in _check_integrity
    raise Exception('Dataset not found or corrupted.')
Exception: Dataset not found or corrupted.
```

![image](https://user-images.githubusercontent.com/22118253/89740265-32f1bc80-da55-11ea-8f3e-84509f94775c.png)

Is it my code that's incorrect? 

Best,
Sibo

**Comment by Sibozhu** [comment]
update: OTB dataset is working, GOT-10k isn't

**Comment by Sibozhu** [comment]
update: Can solve this problem by manually download dataset.
